version: '2'

services:
    mysql:
      container_name: mysql
      image: mysql:8
      env_file: .env
      restart: always
      # The native password plugin is required by the lutece container entrypoint script
      command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
      ports:
        - "3306:3306"
      volumes:
        - db:/var/lib/mysql
        - ./.secrets/:/run/secrets/

    lutece:
      container_name: lutece    
      image: ghcr.io/jhu-sheridan-libraries/lutece-init:0.8
      env_file: .env
      depends_on:
        - mysql
      ports:
        - "8080:8080"
      volumes:
        - ./data/:/data/
        - ./.secrets/:/run/secrets/

volumes:
  db:
    driver: local
