version: '2'

services:
    mysql:
      container_name: mysql
      image: mysql/mysql-server:5.6
      env_file: .env
      restart: always
      volumes:
        - db:/var/lib/mysql
        - ./.secrets/:/run/secrets/

    lutece-init:
      image: jhulibraries/lutece-init:0.4
      container_name: lutece-init
      env_file: .env
      depends_on:
        - mysql
      volumes:
        - ./.webapps/:/webapps
        - ./.secrets/:/run/secrets/
        - ./data/:/data/

    tomcat:
      container_name: tomcat    
      image: tomcat:8
      env_file: .env
      depends_on:
        - lutece-init
      ports:
        - "8080:8080"
      volumes:
        - ./.webapps/:/usr/local/tomcat/webapps/
        - ./.secrets/:/run/secrets/
        - ./server.xml:/usr/local/tomcat/conf/server.xml

    nginx:
      container_name: nginx
      image:  nginx:1.17.7
      depends_on:
        - tomcat
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./.nginx/conf.d/:/etc/nginx/conf.d/
        - ./.nginx/certs/cert.crt:/etc/nginx/cert.crt
        - ./.nginx/certs/cert.key:/etc/nginx/cert.key


volumes:
  db:
    driver: local
