version: '2'

services:
    mysql:
      container_name: mysql
      image: mysql:8
      env_file: .env
      restart: always
      command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
      volumes:
        - db:/var/lib/mysql
        - ./.secrets/:/run/secrets/

    lutece-init:
      image: jhulibraries/lutece-init:0.6
      container_name: lutece-init
      env_file: .env
      depends_on:
        - mysql
      volumes:
        - ./.webapps/:/webapps
        - ./.secrets/:/run/secrets/
        - ./data/:/data/

    tomcat:
      container_name: tomcat    
      image: tomcat:8
      env_file: .env
      depends_on:
        - lutece-init
      ports:
        - "8080:8080"
      volumes:
        - ./.webapps/:/usr/local/tomcat/webapps/
        - ./.secrets/:/run/secrets/
        - ./server.xml:/usr/local/tomcat/conf/server.xml

volumes:
  db:
    driver: local
