version: '2'

services:
    mysql:
      container_name: mysql
      image: mysql/mysql-server:5.6
      env_file: .env
      restart: always
      volumes:
        - db:/var/lib/mysql
        - ./.secrets/:/run/secrets/

    lutece-init:
      build: lutece-init/
      image: jhulibraries/lutece-init:0.1
      container_name: lutece-init
      env_file: .env
      depends_on:
        - mysql
      volumes:
        - ./lutece.war:/lutece.war
        - ./.webapps/:/webapps
        - ./.secrets/:/run/secrets/
        - ./lutece.sql:/lutece.sql

    tomcat:
      container_name: tomcat    
      image: tomcat:8
      env_file: .env
      depends_on:
        - lutece-init
      ports:
        - "8080:8080"
      volumes:
        - ./.webapps/:/usr/local/tomcat/webapps/
        - ./.secrets/:/run/secrets/

volumes:
  db:
    driver: local
