version: '2'

services:
    mysql:
      container_name: mysql
      image: mysql:8
      env_file: .env
      restart: always
      volumes:
        - db:/var/lib/mysql
        - ./.secrets/:/run/secrets/

    lutece:
      container_name: lutece    
      image: jhulibraries/lutece-init:0.7
      env_file: .env
      depends_on:
        - mysql
      ports:
        - "8080:8080"
      volumes:
        - ./data/:/data/      
        - ./.secrets/:/run/secrets/

volumes:
  db:
    driver: local
